model_personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "medium"
approvals_reviewer = "guardian_subagent"

[features]
unified_exec = true
shell_snapshot = true
apps = true
steer = true
personality = true
multi_agent = true
prevent_idle_sleep = true
js_repl = true
memories = true
external_migration = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.qmd]
command = "qmd"
args = ["mcp"]

[mcp_servers.fff]
command = "fff-mcp"
args = []

[mcp_servers.fff.tools.find_files]
approval_mode = "approve"

[mcp_servers.fff.tools.grep]
approval_mode = "approve"

[mcp_servers.fff.tools.multi_grep]
approval_mode = "approve"

[mcp_servers.react-grab-mcp]
command = "npx"
args = ["-y", "@react-grab/mcp", "--stdio"]

[mcp_servers.logpilot]
command = "logpilot"
args = ["mcp-server"]

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[notice.external_config_migration_prompts]
home_last_prompted_at = 1777243300

[tui]
status_line = ["model-with-reasoning", "context-remaining", "five-hour-limit", "context-used"]
theme = "kanagawa"

[tui.model_availability_nux]
"gpt-5.5" = 1

[plugins."github@openai-curated"]
enabled = true

[plugins."claude-md-management@claude-plugins-official"]
enabled = true

[plugins."code-simplifier@claude-plugins-official"]
enabled = true

[plugins."context7@claude-plugins-official"]
enabled = true

[plugins."frontend-design@claude-plugins-official"]
enabled = true

[plugins."learning-output-style@claude-plugins-official"]
enabled = true

[plugins."codex@openai-codex"]
enabled = true

[plugins."plannotator@plannotator"]
enabled = true

[marketplaces.claude-plugins-official]
last_updated = "2026-04-30T03:09:11Z"
last_revision = "0742692199b49af5c6c33cd68ee674fb2e679d50"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.plannotator]
last_updated = "2026-04-30T03:09:17Z"
last_revision = "a68463b6a4f5b3aba5367905961fb650f8e6f5a3"
source_type = "git"
source = "https://github.com/backnotprop/plannotator.git"

[marketplaces.worktrunk]
last_updated = "2026-04-26T22:42:28Z"
source_type = "git"
source = "https://github.com/max-sixty/worktrunk.git"
