app = "ai-tools-itman-fyi"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  OPENAI_BASE_URL = "https://openrouter.ai/api/v1"
  OPENAI_MODEL = "openrouter/free"
  OPENAI_EMBEDDING_MODEL = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
